(in-package :%wild-engine.core.vk)

(defparameter *sys-hash* (make-hash-table))

(defparameter *last-time* 0)
(defparameter *frame-count* 0)

(defmacro defsys-set (name)
  (let ((set-sym (we.u:create-symbol 'set- name)))
    `(defun ,set-sym (sym val)
       (declare (optimize (speed 3) (debug 0) (safety 0)))
       (setf (getf (gethash sym *sys-hash*) ',name) val))))

(defmacro defsys-get (name)
  (let ((get-sym (we.u:create-symbol 'get- name)))
    `(progn
       (defun ,get-sym (sym)
	 (declare (optimize (speed 3) (debug 0) (safety 0)))
	 (getf (gethash sym *sys-hash*) ',name))
       ;; export get fun
       (export ',name))))

(defsys-set window)
(defsys-get window)

(defsys-set instance)
(defsys-get instance)
(defsys-set dbg-reporter)
(defsys-get dbg-reporter)

(defsys-set surface)
(defsys-get surface)

(defsys-set gpu)
(defsys-get gpu)
(defsys-set gpu-surface-capabilities)
(defsys-get gpu-surface-capabilities)
(defsys-set gpu-formats)
(defsys-get gpu-formats)
(defsys-set gpu-present-modes)
(defsys-get gpu-present-modes)
(defsys-set gpu-features)
(defsys-get gpu-features)
(defsys-set gpu-properties)
(defsys-get gpu-properties)
(defsys-set gpu-device-queue-family-properties)
(defsys-get gpu-device-queue-family-properties)
(defsys-set gpu-memory-properties)
(defsys-get gpu-memory-properties)

(defsys-set device)
(defsys-get device)
(defsys-set device-gqindex)
(defsys-get device-gqindex)
(defsys-set device-tqindex)
(defsys-get device-tqindex)
(defsys-set device-cqindex)
(defsys-get device-cqindex)
(defsys-set device-pqindex)
(defsys-get device-pqindex)
(defsys-set device-gqueue)
(defsys-get device-gqueue)
(defsys-set device-tqueue)
(defsys-get device-tqueue)
(defsys-set device-cqueue)
(defsys-get device-cqueue)
(defsys-set device-pqueue)
(defsys-get device-pqueue)

(defsys-set swapchain)
(defsys-get swapchain)
(defsys-set swapchain-format)
(defsys-get swapchain-format)
(defsys-set swapchain-images)
(defsys-get swapchain-images)
(defsys-set swapchain-image-views)
(defsys-get swapchain-image-views)

(defsys-set pipeline-cache)
(defsys-get pipeline-cache)

(defsys-set render-pass)
(defsys-get render-pass)

(defsys-set frame-buffers)
(defsys-get frame-buffers)

(defsys-set cmd-pool-graphics)
(defsys-get cmd-pool-graphics)
(defsys-set cmd-pool-transfer)
(defsys-get cmd-pool-transfer)
(defsys-set cmd-pool-compute)
(defsys-get cmd-pool-compute)

(defsys-set cmds-graphics)
(defsys-get cmds-graphics)
(defsys-set cmds-transfer)
(defsys-get cmds-transfer)
(defsys-set cmds-compute)
(defsys-get cmds-compute)
;; (defsys-set currend-gcmd)
;; (defsys-get currend-gcmd)
(defsys-set current-gcmd-index)
(defsys-get current-gcmd-index)

(defsys-set fences)
(defsys-get fences)
(defsys-set present-complete)
(defsys-get present-complete)
(defsys-set render-complete)
(defsys-get render-complete)

(defsys-set depth-format)
(defsys-get depth-format)
(defsys-set depth-image)
(defsys-get depth-image)
(defsys-set depth-image-view)
(defsys-get depth-image-view)
(defsys-set depth-memory)
(defsys-get depth-memory)

(defparameter *descriptor-pool* nil)
